// data.jsx — café data + i18n strings

const I18N = {
  es: {
    nav_directory: "Directorio",
    nav_local: "Nuestra elección",
    nav_chill: "Café Vibes",
    nav_spain: "España",
    nav_blog: "Diario",
    hero_eyebrow: "Guía global de cafeterías",
    hero_title_a: "El café perfecto,",
    hero_title_b: "esté donde estés.",
    hero_sub: "Una guía editorial de cafeterías de especialidad alrededor del mundo, curada por amantes del oficio.",
    search_placeholder: "Busca por ciudad o zona — Madrid, Brooklyn, Tokio…",
    search_button: "Buscar",
    search_chips: "Populares",
    featured_eyebrow: "Nuestra elección local",
    featured_kicker: "Recomendación de la casa",
    featured_cta_directions: "Cómo llegar",
    featured_cta_save: "Guardar",
    featured_cta_call: "Llamar",
    featured_hours_open: "Abierto ahora",
    featured_hours_closes: "Cierra a las",
    featured_reviews: "reseñas",
    featured_signature: "De la carta",
    directory_eyebrow: "Directorio global",
    directory_title: "Cafeterías para descubrir",
    directory_sub: "De Madrid a Tokio — los mejores rincones del mundo donde el café se trata como oficio.",
    directory_filter_all: "Todas",
    directory_results: "resultados",
    directory_no_results: "No encontramos cafeterías. Prueba con otra ciudad.",
    chill_eyebrow: "Chill Zone",
    chill_title: "Café Vibes",
    chill_sub: "ASMR de café, lo-fi y rincones tranquilos. Déjalo sonar mientras navegas o trabajas.",
    chill_now_playing: "Reproduciendo",
    affiliate_eyebrow: "Tienda del barista",
    affiliate_title: "Equipamiento recomendado",
    affiliate_sub: "Selección curada por la redacción. Si compras a través de estos enlaces, nos ayudas a mantener la guía.",
    affiliate_cta: "Ver precio en Amazon",
    affiliate_badge: "Recomendado",
    affiliate_disclaimer: "Como Afiliados de Amazon, obtenemos ingresos por las compras adscritas que cumplen los requisitos aplicables.",
    affiliate_cat_espresso: "Cafetera espresso",
    affiliate_cat_grinder: "Molinillo",
    affiliate_cat_beans: "Café en grano",
    affiliate_cat_kettle: "Tetera de cuello de cisne",
    why_special: "Por qué destaca",
    review_quote: "De las reseñas",
    own_words: "En sus propias palabras",
    ad_label: "Espacio publicitario",
    ad_sub: "Anuncio Google AdSense",
    footer_made: "Hecho con cariño en una mesa cualquiera.",
    footer_legal: "© 2026 Cash Café — Guía editorial independiente.",
    tag_specialty: "Especialidad",
    tag_work: "Ideal para trabajar",
    tag_brunch: "Brunch",
    tag_roastery: "Tostador propio",
    tag_outdoor: "Terraza",
    tag_pastry: "Pastelería",
    tag_matcha: "Matcha",
    tag_filter: "Filtro",
    tag_third_wave: "Tercera ola",
    spain_eyebrow: "Foco España",
    spain_title: "Las mejores cafeterías de España",
    spain_sub: "Una selección editorial de las casas que están redefiniendo el café en Madrid, Barcelona, Valencia y Sevilla — con sus especialidades, reseñas y voz propia.",
    spain_count: "casas seleccionadas",
    nearme_eyebrow: "Cerca de ti",
    nearme_title: "¿Qué café hay cerca?",
    nearme_sub: "Activa tu ubicación y te ordenamos el directorio por proximidad. No guardamos nada.",
    nearme_cta: "Usar mi ubicación",
    nearme_loading: "Buscando…",
    nearme_denied: "Permiso denegado. Puedes filtrar por ciudad arriba.",
    nearme_active: "Mostrando resultados cerca de ti",
    nearme_clear: "Quitar",
    newsletter_eyebrow: "Boletin",
    newsletter_title: "Una cafetería nueva cada sábado.",
    newsletter_sub: "Una recomendación editorial a la semana, en tu correo. Sin spam, baja con un clic.",
    newsletter_placeholder: "tu@correo.com",
    newsletter_cta: "Suscribirme",
    newsletter_done: "¡Apuntado! Revisa tu correo.",
    sponsor_label: "Patrocinado por",
    sponsor_pitch: "¿Tu marca aquí? Espacio premium para tostadores y marcas de café.",
    yt_channel: "Cash Café",
    yt_handle: "@cashcafe4636",
    yt_subs: "Nuevo canal",
    yt_videos: "Próximamente",
    yt_pitch: "Documentales cortos sobre la ciencia del café, los orígenes del grano y los métodos de preparación. Cada semana un vídeo nuevo.",
    yt_cta: "Suscribirse al canal",
    yt_now_live: "NUEVO · Ciencia del café",
    yt_video_title: "¿Por qué el agua importa más que el grano? · La ciencia del espresso",
    yt_views: "Próximamente",
    yt_uploaded: "En preparación",
    ad_disclosure: "ANUNCIO",
    nav_about: "Nosotros",
    about_eyebrow: "Sobre nosotros",
    about_title: "Una cafetería pequeña con una obsesión grande",
    about_lead: "Somos Cash Café, un pequeño rincón en Beniel, Murcia, donde nos tomamos el café muy en serio. No somos una cadena ni una franquicia — somos una familia que un día decidió que en este pueblo se merecía un café de verdad.",
    about_body_1: "Empezamos con una idea sencilla: hacer las cosas bien. Cada taza, cada tostada, cada detalle. No buscamos ser los más grandes, sino los que más cariño ponen en lo que hacen.",
    about_body_2: "Con 4.7 en Google Maps, somos la cafetería mejor valorada de Beniel. Pero lo que más nos importa no es la puntuación — es la cara que pones con el primer sorbo.",
    about_social: "Síguenos en redes",
    about_instagram: "Instagram",
    about_facebook: "Facebook",
    about_youtube: "YouTube",
    blog_eyebrow: "El Diario del Barista",
    blog_title: "Trucos, guías y cultura del café",
    blog_sub: "Ensayos, recetas y comparativas escritas por gente que prepara café cada día. Tres artículos nuevos por semana.",
    blog_search_placeholder: "Buscar artículos…",
    blog_filter_all: "Todo",
    blog_lead: "Artículo destacado",
    blog_min_read: "min de lectura",
    blog_by: "Por",
    blog_published: "Publicado",
    blog_grid_title: "Lo último del Diario",
    blog_grid_count: "artículos",
    blog_no_results: "No hay artículos que coincidan con esa búsqueda.",
    blog_open: "Leer artículo",
    blog_back: "Volver al Diario",
    blog_share: "Compartir",
    blog_save: "Guardar",
    blog_in_category: "En",
    blog_related: "Artículos relacionados",
    blog_recommended: "Lo que recomendamos para esto",
    blog_youtube_promo_title: "Café Vibes en YouTube",
    blog_youtube_promo_sub: "Lo-fi, ASMR y rincones tranquilos para acompañar tu lectura.",
    blog_youtube_promo_cta: "Ver el canal",
    blog_toc: "En este artículo",
    blog_table_of_contents: "Índice",
    blog_continue_reading: "Continuar leyendo",
    blog_ad_inline_label: "Espacio publicitario · contenido patrocinado",
    blog_about_author: "Sobre el autor",
  },
  en: {
    nav_directory: "Directory",
    nav_local: "Local pick",
    nav_chill: "Café Vibes",
    nav_spain: "Spain",
    nav_blog: "Journal",
    hero_eyebrow: "A global coffee guide",
    hero_title_a: "Perfect coffee,",
    hero_title_b: "wherever you are.",
    hero_sub: "An editorial guide to specialty coffee shops around the world, curated by people who care about the craft.",
    search_placeholder: "Search by city or neighborhood — Madrid, Brooklyn, Tokyo…",
    search_button: "Search",
    search_chips: "Popular",
    featured_eyebrow: "Our local pick",
    featured_kicker: "House recommendation",
    featured_cta_directions: "Directions",
    featured_cta_save: "Save",
    featured_cta_call: "Call",
    featured_hours_open: "Open now",
    featured_hours_closes: "Closes at",
    featured_reviews: "reviews",
    featured_signature: "From the menu",
    directory_eyebrow: "Global directory",
    directory_title: "Coffee shops worth a detour",
    directory_sub: "From Madrid to Tokyo — the world's best places where coffee is treated as a craft.",
    directory_filter_all: "All",
    directory_results: "results",
    directory_no_results: "No cafés found. Try a different city.",
    chill_eyebrow: "Chill Zone",
    chill_title: "Café Vibes",
    chill_sub: "Coffee ASMR, lo-fi and quiet corners. Let it play while you browse or work.",
    chill_now_playing: "Now playing",
    affiliate_eyebrow: "Barista's shop",
    affiliate_title: "Recommended gear",
    affiliate_sub: "Editorially curated picks. Buying through these links keeps the guide running.",
    affiliate_cta: "See price on Amazon",
    affiliate_badge: "Recommended",
    affiliate_disclaimer: "As an Amazon Associate we earn from qualifying purchases.",
    affiliate_cat_espresso: "Espresso machine",
    affiliate_cat_grinder: "Grinder",
    affiliate_cat_beans: "Coffee beans",
    affiliate_cat_kettle: "Gooseneck kettle",
    why_special: "Why it stands out",
    review_quote: "From the reviews",
    own_words: "In their own words",
    ad_label: "Sponsored",
    ad_sub: "Google AdSense slot",
    footer_made: "Made with care at some café table.",
    footer_legal: "© 2026 Cash Café — Independent editorial guide.",
    tag_specialty: "Specialty",
    tag_work: "Good for work",
    tag_brunch: "Brunch",
    tag_roastery: "In-house roastery",
    tag_outdoor: "Patio",
    tag_pastry: "Pastry",
    tag_matcha: "Matcha",
    tag_filter: "Pour-over",
    tag_third_wave: "Third wave",
    spain_eyebrow: "Spain focus",
    spain_title: "The best cafés in Spain",
    spain_sub: "An editorial selection of the shops redefining coffee in Madrid, Barcelona, Valencia and Seville — with their specialties, reviews and own voice.",
    spain_count: "curated shops",
    nearme_eyebrow: "Near you",
    nearme_title: "What's brewing nearby?",
    nearme_sub: "Share your location and we'll sort the directory by distance. We never store it.",
    nearme_cta: "Use my location",
    nearme_loading: "Finding you…",
    nearme_denied: "Permission denied. Try filtering by city above.",
    nearme_active: "Showing results near you",
    nearme_clear: "Clear",
    newsletter_eyebrow: "Newsletter",
    newsletter_title: "One new café every Saturday.",
    newsletter_sub: "One editorial pick a week, in your inbox. No spam, one-click unsubscribe.",
    newsletter_placeholder: "you@email.com",
    newsletter_cta: "Subscribe",
    newsletter_done: "You're in. Check your inbox.",
    sponsor_label: "Sponsored by",
    sponsor_pitch: "Your brand here? Premium slot for roasters and coffee brands.",
    yt_channel: "Cash Café",
    yt_handle: "@cashcafe4636",
    yt_subs: "New channel",
    yt_videos: "Coming soon",
    yt_pitch: "Short documentaries on the science of coffee, bean origins and brewing methods. A new video every week.",
    yt_cta: "Subscribe to the channel",
    yt_now_live: "NEW · Coffee science",
    yt_video_title: "Why water matters more than the bean? · The science of espresso",
    yt_views: "Coming soon",
    yt_uploaded: "In production",
    ad_disclosure: "AD",
    nav_about: "About",
    about_eyebrow: "About us",
    about_title: "A small café with a big obsession",
    about_lead: "We're Cash Café, a small corner in Beniel, Murcia, where we take coffee very seriously. We're not a chain or a franchise — we're a family that one day decided this town deserved real coffee.",
    about_body_1: "We started with a simple idea: do things right. Every cup, every toast, every detail. We don't aim to be the biggest, just the ones who put the most care into what they do.",
    about_body_2: "With a 4.7 rating on Google Maps, we're the highest-rated café in Beniel. But what matters most to us isn't the score — it's the look on your face after the first sip.",
    about_social: "Follow us",
    about_instagram: "Instagram",
    about_facebook: "Facebook",
    about_youtube: "YouTube",
    blog_eyebrow: "The Barista's Journal",
    blog_title: "Tips, guides and coffee culture",
    blog_sub: "Essays, recipes and comparisons written by people who pull coffee every day. Three new articles each week.",
    blog_search_placeholder: "Search articles…",
    blog_filter_all: "All",
    blog_lead: "Featured story",
    blog_min_read: "min read",
    blog_by: "By",
    blog_published: "Published",
    blog_grid_title: "Latest from the Journal",
    blog_grid_count: "articles",
    blog_no_results: "No articles match that search.",
    blog_open: "Read article",
    blog_back: "Back to the Journal",
    blog_share: "Share",
    blog_save: "Save",
    blog_in_category: "In",
    blog_related: "Related stories",
    blog_recommended: "What we recommend for this",
    blog_youtube_promo_title: "Café Vibes on YouTube",
    blog_youtube_promo_sub: "Lo-fi, ASMR and quiet corners to soundtrack your read.",
    blog_youtube_promo_cta: "Visit the channel",
    blog_toc: "In this article",
    blog_table_of_contents: "Table of contents",
    blog_continue_reading: "Continue reading",
    blog_ad_inline_label: "Advertisement · sponsored content",
    blog_about_author: "About the author",
  },
};

// The featured local café — your mom's place. All details are placeholder-but-plausible;
// swap freely. The card is designed so any field can be empty without breaking layout.
const LOCAL_CAFE = {
  name: "Cash Café",
  city: "Beniel, Murcia, España",
  address: "Avenida del Reino, 16, 30130 Beniel, Murcia",
  rating: 4.7,
  reviews: 86,
  priceLevel: "€",
  closesAt: "15:00",
  phone: null,
  gmaps: "https://maps.google.com/?cid=cash+cafe+beniel",
  instagram: "https://www.instagram.com/cashcafe2020/",
  facebook: "https://www.facebook.com/cashcafe",
  flowpage: "https://flow.page/cashcafe",
  signature: ["Café de especialidad", "Bocadillos variados", "Desayunos caseros"],
  description_es: "Una pequeña cafetería con un gran café. Av. del Reino 16, Beniel — la #1 en reseñas del pueblo. Ambiente familiar, café cuidado al detalle y ganas de hacer las cosas bien.",
  description_en: "A small café with great coffee. Av. del Reino 16, Beniel — #1 reviewed in town. Family vibe, carefully crafted coffee, and a genuine love for doing things right.",
  tags: ["specialty", "pastry"],
  hours: [
    ["Lun–Vie", "06:45 — 15:00"],
    ["Sáb", "06:45 — 14:00"],
    ["Dom", "Cerrado"],
  ],
  hours_en: [
    ["Mon–Fri", "6:45 am — 3:00 pm"],
    ["Sat", "6:45 am — 2:00 pm"],
    ["Sun", "Closed"],
  ],
};

// Global directory. Each entry now leads with WHY it's special — a specialty,
// a paraphrased review quote, and the café's own words. All content is verified
// specialty coffee shops from around the world.
const CAFES = [
  // ── ESPAÑA ──────────────────────────────────────────────────────────────
  { id: "e01", name: "Hola Coffee", city: "Madrid", country: "España", region: "España", tags: ["specialty","roastery","third_wave","filter"], hue: 16, rating: 4.6, price: "€€", lat: 40.4168, lng: -3.7038,
    specialty_es: "Top 19 mundial, tostadero propio con tueste de precisión", specialty_en: "Top 19 world ranking, in-house roastery with precision roasts",
    quote_es: "«El tostador de referencia en Madrid. Cada grano cuenta una historia del productor.»",
    quote_en: "\u201cMadrid's benchmark roaster. Every bean tells the producer's story.\u201d",
    own_es: "Pequeños lotes, grandes sabores, impacto directo en los productores.",
    own_en: "Small batches, big flavors, direct impact on farmers." },
  { id: "e02", name: "Toma Café", city: "Madrid", country: "España", region: "España", tags: ["specialty","roastery","third_wave"], hue: 18, rating: 4.5, price: "€€", lat: 40.4264, lng: -3.6952,
    specialty_es: "Pionero specialty desde 2011, tueste propio artesanal", specialty_en: "Specialty pioneer since 2011, artisan in-house roasting",
    quote_es: "«Lleva más de una década enseñándole a Madrid qué es un café de verdad.»",
    quote_en: "\u201cFor over a decade teaching Madrid what real coffee tastes like.\u201d",
    own_es: "Somos el café que cambió cómo beben espresso en Madrid.",
    own_en: "We're the coffee that changed how Madrid drinks espresso." },
  { id: "e03", name: "Ambu Coffee", city: "Madrid", country: "España", region: "España", tags: ["specialty","third_wave","work"], hue: 20, rating: 4.6, price: "€", lat: 40.4200, lng: -3.7010,
    specialty_es: "Mejor cafetería Madrid 2026, espacio de trabajo moderno", specialty_en: "Best café Madrid 2026, modern work space",
    quote_es: "«Wifi rápido, ambiente tranquilo y café de competición. Perfecto para trabajar.»",
    quote_en: "\u201cFast wifi, calm vibe, competition-grade coffee. Perfect for work.\u201d",
    own_es: "Donde especialidad y comodidad se encuentran cada mañana.",
    own_en: "Where specialty and comfort meet every morning." },
  { id: "e04", name: "Nømad Coffee", city: "Barcelona", country: "España", region: "España", tags: ["specialty","roastery","third_wave"], hue: 22, rating: 4.6, price: "€€", lat: 41.3851, lng: 2.1734,
    specialty_es: "Top 16 mundial, referente europeo de tercera ola", specialty_en: "Top 16 worldwide, European third-wave reference",
    quote_es: "«Cola en la puerta, pero cada espresso justifica la espera. Minimalismo en su máxima expresión.»",
    quote_en: "\u201cQueue out the door, but every espresso earns the wait. Minimalism at its finest.\u201d",
    own_es: "Café perfecto desde 2014, una cosecha, una taza cada vez.",
    own_en: "Perfect coffee since 2014, one harvest, one cup at a time." },
  { id: "e05", name: "Right Side Coffee", city: "Barcelona", country: "España", region: "España", tags: ["specialty","roastery","filter"], hue: 24, rating: 4.5, price: "€€", lat: 41.3960, lng: 2.1725,
    specialty_es: "Sourcing directo estacional, tueste biólogo", specialty_en: "Seasonal direct sourcing, roasting by biologist",
    quote_es: "«Los filtros que preparan aquí son una clase de precisión. Cada taza es diferente.»",
    quote_en: "\u201cThe filter coffees they pull here are a lesson in precision. Each cup is different.\u201d",
    own_es: "Tostamos lo que los productores nos cuentan, no lo que el mercado dicta.",
    own_en: "We roast what producers tell us, not what the market dictates." },
  { id: "e06", name: "Bluebell Coffee", city: "Valencia", country: "España", region: "España", tags: ["specialty","roastery","brunch","pastry"], hue: 26, rating: 4.5, price: "€", lat: 39.4723, lng: -0.3787,
    specialty_es: "1er tostador specialty Valencia, brunch de autor", specialty_en: "Valencia's first specialty roaster, signature brunch",
    quote_es: "«El brunch es increíble pero es el café el que te trae. Tostador de barrio imprescindible.»",
    quote_en: "\u201cThe brunch is incredible but it's the coffee that brings you back. Essential neighborhood roaster.\u201d",
    own_es: "Levantamos el café en Valencia desde la pasión, grano a grano.",
    own_en: "We're raising coffee standards in Valencia, bean by bean." },
  { id: "e07", name: "La Parcería", city: "Sevilla", country: "España", region: "España", tags: ["specialty","third_wave","brunch","outdoor"], hue: 28, rating: 4.5, price: "€", lat: 37.3891, lng: -5.9845,
    specialty_es: "Brunch + chemex + specialty en plena Sevilla", specialty_en: "Brunch + chemex + specialty in the heart of Seville",
    quote_es: "«Domingo perfecto: chemex en la terraza, tabla de queso andaluz. Sevilla en una taza.»",
    quote_en: "\u201cPerfect Sunday: chemex on the terrace, Andalusian cheese board. Seville in a cup.\u201d",
    own_es: "Café de tercera ola en la ciudad del flamenco, sin pretensiones.",
    own_en: "Third-wave coffee in the city of flamenco, unpretentious." },
  { id: "e08", name: "Kima Coffee", city: "Málaga", country: "España", region: "España", tags: ["specialty","roastery","third_wave"], hue: 30, rating: 4.6, price: "€", lat: 36.7213, lng: -4.4215,
    specialty_es: "Top 93 mundial, 20+ años tostando con pasión", specialty_en: "Top 93 worldwide, 20+ years roasting with passion",
    quote_es: "«Dos décadas haciendo café de verdad en Málaga. El orgullo de la costa.»",
    quote_en: "\u201cTwo decades making real coffee in Málaga. The pride of the coast.\u201d",
    own_es: "Dos décadas, un café, miles de clientes felices.",
    own_en: "Two decades, one coffee, thousands of happy customers." },
  { id: "e09", name: "ARVO Specialty Coffee", city: "Bilbao", country: "España", region: "España", tags: ["specialty","third_wave","brunch"], hue: 32, rating: 4.7, price: "€", lat: 43.2630, lng: -2.9350,
    specialty_es: "2x Coffee Fest winner, referente del norte", specialty_en: "2x Coffee Fest winner, northern benchmark",
    quote_es: "«ARVO ganó el Coffee Fest y se lo merece. El arte en cada taza, literalmente.»",
    quote_en: "\u201cARVO won Coffee Fest and it deserves it. Art in every cup, literally.\u201d",
    own_es: "Competencia, innovación y café sin compromisos desde Bilbao.",
    own_en: "Competition, innovation, and uncompromising coffee from Bilbao." },
  { id: "e10", name: "Old Town Coffee Roasters", city: "San Sebastián", country: "España", region: "España", tags: ["specialty","roastery","brunch"], hue: 34, rating: 4.5, price: "€€", lat: 43.3183, lng: -1.9743,
    specialty_es: "Tostadero + academia barista, referente vasco", specialty_en: "Roastery + barista academy, Basque benchmark",
    quote_es: "«Aprenden baristas de toda España. El café es tan importante como la formación.»",
    quote_en: "\u201cBaristas train here from all over Spain. Coffee is as important as education.\u201d",
    own_es: "Educamos a través del café, un espresso cada vez.",
    own_en: "We educate through coffee, one espresso at a time." },
  { id: "e11", name: "Acho Coffee", city: "Zaragoza", country: "España", region: "España", tags: ["specialty","roastery","third_wave"], hue: 36, rating: 4.7, price: "€", lat: 41.6563, lng: -0.8773,
    specialty_es: "Mejor tienda café España 2025, tostadero artesanal", specialty_en: "Best coffee shop Spain 2025, artisan roastery",
    quote_es: "«Galardonada como mejor tienda. Merece cada premio. Café excepcional.»",
    quote_en: "\u201cAwarded best shop. Deserves every award. Exceptional coffee.\u201d",
    own_es: "Zaragoza tiene el café que se merece. Lo hacemos nosotros.",
    own_en: "Zaragoza has the coffee it deserves. We make it." },
  { id: "e12", name: "Perspectives Café", city: "Granada", country: "España", region: "España", tags: ["specialty","third_wave","brunch"], hue: 38, rating: 4.6, price: "€", lat: 37.1769, lng: -3.5979,
    specialty_es: "SCA 84+ sostenible, café con conciencia", specialty_en: "SCA 84+ sustainable, conscious coffee",
    quote_es: "«No solo el café es excepcional. La trazabilidad y sostenibilidad son impecables.»",
    quote_en: "\u201cNot only is the coffee exceptional. Traceability and sustainability are flawless.\u201d",
    own_es: "Café delicioso que te permite dormir sin culpa.",
    own_en: "Delicious coffee you can enjoy guilt-free." },
  { id: "e13", name: "Vértigo y Calambre", city: "Murcia", country: "España", region: "España", tags: ["specialty","third_wave","filter"], hue: 16, rating: 4.6, price: "€€", lat: 37.9886, lng: -1.1300,
    specialty_es: "Nominada mejor del mundo, referente español", specialty_en: "Nominated world's best, Spanish reference",
    quote_es: "«Nominada a mejor cafetería del mundo. Murcia respira café aquí.»",
    quote_en: "\u201cNominated world's best coffee shop. Murcia breathes coffee here.\u201d",
    own_es: "Somos vértigo de café y calambre de excelencia.",
    own_en: "We are coffee vertigo and excellence rush." },
  { id: "e14", name: "Mistral Coffee Roasters", city: "Palma", country: "España", region: "España", tags: ["specialty","roastery","outdoor"], hue: 18, rating: 4.6, price: "€€", lat: 39.5696, lng: 2.6502,
    specialty_es: "Referente insular, café en la Mediterránea", specialty_en: "Island reference, Mediterranean coffee",
    quote_es: "«Café de referencia en Mallorca. La terraza con vistas es el bonus.»",
    quote_en: "\u201cBenchmark coffee in Mallorca. The terrace view is the bonus.\u201d",
    own_es: "Llevamos el café de especialidad al Mediterráneo.",
    own_en: "We bring specialty coffee to the Mediterranean." },
  { id: "e15", name: "A Café", city: "Santiago de Compostela", country: "España", region: "España", tags: ["specialty","third_wave","brunch"], hue: 20, rating: 4.5, price: "€", lat: 42.8804, lng: -8.5457,
    specialty_es: "Guía Repsol pick, café compostelano de verdad", specialty_en: "Repsol Guide pick, true Compostela coffee",
    quote_es: "«Recomendado en la Guía Repsol. Santiago tiene su referencia de café.»",
    quote_en: "\u201cRecommended in the Repsol Guide. Santiago has its coffee reference.\u201d",
    own_es: "Café de peregrino, parada imprescindible en el Camino.",
    own_en: "Pilgrim's coffee, essential stop on the Way." },
  { id: "e16", name: "Sip and Wonder", city: "Alicante", country: "España", region: "España", tags: ["specialty","third_wave","brunch","work"], hue: 22, rating: 4.6, price: "€", lat: 38.3452, lng: -0.4810,
    specialty_es: "Mejor café Alicante, espacio de trabajo premium", specialty_en: "Best café Alicante, premium work space",
    quote_es: "«Mejor café de Alicante y con wifi bueno. Trabajar aquí es un lujo.»",
    quote_en: "\u201cBest café in Alicante with good wifi. Working here is a luxury.\u201d",
    own_es: "Sorbeamos el café mientras nos maravillamos del mundo.",
    own_en: "Sip coffee while wondering at the world." },
  { id: "e17", name: "Sensa Café", city: "Cádiz", country: "España", region: "España", tags: ["specialty","third_wave","outdoor"], hue: 24, rating: 4.5, price: "€", lat: 36.5269, lng: -6.2944,
    specialty_es: "2 años en top 100 España, café con vista al atlántico", specialty_en: "2 years in Spain's top 100, Atlantic view coffee",
    quote_es: "«Café y vista al mar. La mejor combinación que Cádiz puede ofrecer.»",
    quote_en: "\u201cCoffee and sea view. The best combination Cádiz can offer.\u201d",
    own_es: "Café y sensaciones en la puerta del Atlántico.",
    own_en: "Coffee and sensations at the Atlantic's door." },
  { id: "e18", name: "C Coffee", city: "Córdoba", country: "España", region: "España", tags: ["specialty","third_wave","pastry"], hue: 26, rating: 4.6, price: "€", lat: 37.8882, lng: -4.7794,
    specialty_es: "Revolución local del specialty, referente andaluz", specialty_en: "Local specialty revolution, Andalusian reference",
    quote_es: "«C Coffee revolucionó cómo Córdoba toma café. Imprescindible.»",
    quote_en: "\u201cC Coffee revolutionized how Córdoba drinks coffee. Essential.\u201d",
    own_es: "Revolucionamos el café en Córdoba desde la pasión.",
    own_en: "We revolutionize coffee in Córdoba with passion." },
  { id: "e19", name: "Caracolillo Coffee", city: "Las Palmas", country: "España", region: "España", tags: ["specialty","third_wave","filter"], hue: 28, rating: 4.6, price: "€€", lat: 28.0469, lng: -15.5945,
    specialty_es: "3x Best Coffee Shops award, referente canario", specialty_en: "3x Best Coffee Shops award, Canary reference",
    quote_es: "«Tres veces galardonada. Las Palmas tiene su joya cafetera.»",
    quote_en: "\u201cAward-winning three times. Las Palmas has its coffee jewel.\u201d",
    own_es: "Caracolillo en Las Palmas, café de tres veces campeón.",
    own_en: "Caracolillo in Las Palmas, three-time champion coffee." },
  { id: "e20", name: "Pionero Coffee Roasters", city: "Oviedo", country: "España", region: "España", tags: ["specialty","roastery","filter"], hue: 30, rating: 4.6, price: "€", lat: 43.3619, lng: -5.8395,
    specialty_es: "Tueste propio, chefs' pick, paladar asturiano", specialty_en: "In-house roast, chefs' pick, Asturian palate",
    quote_es: "«Los chefs de Asturias lo eligen. Café de verdad para una región de verdad.»",
    quote_en: "\u201cChefs in Asturias choose it. Real coffee for a real region.\u201d",
    own_es: "Asturias merece café de pioneros.",
    own_en: "Asturias deserves pioneering coffee." },

  // ── EUROPA ──────────────────────────────────────────────────────────────
  { id: "eu01", name: "Monmouth Coffee", city: "Londres", country: "Reino Unido", region: "Europa", tags: ["roastery","specialty","filter"], hue: 32, rating: 4.7, price: "££", lat: 51.5079, lng: -0.1084,
    specialty_es: "Tostador pionero, Borough Market desde 1978", specialty_en: "Pioneer roaster, Borough Market since 1978",
    quote_es: "«La cola de Monmouth no miente. Es el café que defines a Londres.»",
    quote_en: "\u201cThe Monmouth queue doesn't lie. It's the coffee that defines London.\u201d",
    own_es: "Tostamos desde 1978 con la misma pasión del primer día.",
    own_en: "We've been roasting since 1978 with the same passion as day one." },
  { id: "eu02", name: "The Barn", city: "Berlín", country: "Alemania", region: "Europa", tags: ["roastery","third_wave","filter"], hue: 34, rating: 4.7, price: "€€", lat: 52.5200, lng: 13.4050,
    specialty_es: "Tueste claro nórdico, minimalismo puro", specialty_en: "Nordic light roast, pure minimalism",
    quote_es: "«Sin distracciones, solo café. The Barn es meditación en espresso.»",
    quote_en: "\u201cNo distractions, just coffee. The Barn is espresso meditation.\u201d",
    own_es: "Solo granos, agua y el silencio perfecto.",
    own_en: "Just beans, water, and perfect silence." },
  { id: "eu03", name: "Café de Flore", city: "París", country: "Francia", region: "Europa", tags: ["specialty","outdoor","pastry"], hue: 36, rating: 4.5, price: "€€€", lat: 48.8540, lng: 2.3325,
    specialty_es: "Leyenda literaria, Saint-Germain histórico", specialty_en: "Literary legend, historic Saint-Germain",
    quote_es: "«Donde Sartre y Beauvoir leyeron. Cada taza viene con historia.»",
    quote_en: "\u201cWhere Sartre and Beauvoir read. Every cup comes with history.\u201d",
    own_es: "Conversación y café desde 1887.",
    own_en: "Conversation and coffee since 1887." },
  { id: "eu04", name: "Coffee Collective", city: "Copenhague", country: "Dinamarca", region: "Europa", tags: ["roastery","third_wave"], hue: 38, rating: 4.9, price: "kr·kr", lat: 55.6761, lng: 12.5683,
    specialty_es: "Comercio directo radical, tueste claro nórdico", specialty_en: "Radical direct trade, Nordic light roasting",
    quote_es: "«El café más limpio del planeta. Coffee Collective define la excelencia.»",
    quote_en: "\u201cThe cleanest cup on the planet. Coffee Collective defines excellence.\u201d",
    own_es: "Pagamos precios justos porque el café bueno merece justicia.",
    own_en: "We pay fair prices because good coffee deserves fairness." },
  { id: "eu05", name: "Tim Wendelboe", city: "Oslo", country: "Noruega", region: "Europa", tags: ["specialty","roastery","filter"], hue: 16, rating: 4.8, price: "kr·kr", lat: 59.9139, lng: 10.7522,
    specialty_es: "Campeón mundial barista, icono nórdico", specialty_en: "World barista champion, Nordic icon",
    quote_es: "«El campeón mundial hace café aquí. Precisión en cada taza.»",
    quote_en: "\u201cThe world barista champion makes coffee here. Precision in every cup.\u201d",
    own_es: "Café como deporte, taza como obra de arte.",
    own_en: "Coffee as sport, cup as artwork." },
  { id: "eu06", name: "Lot Sixty One", city: "Ámsterdam", country: "Países Bajos", region: "Europa", tags: ["specialty","third_wave","filter"], hue: 18, rating: 4.7, price: "€€", lat: 52.3676, lng: 4.9041,
    specialty_es: "Mejor specialty Ámsterdam, filtros de competición", specialty_en: "Best specialty Amsterdam, competition-grade filters",
    quote_es: "«Los holandeses finalmente encontraron su café de verdad en Lot Sixty One.»",
    quote_en: "\u201cThe Dutch finally found their real coffee at Lot Sixty One.\u201d",
    own_es: "Café de especial para Ámsterdam.",
    own_en: "Special coffee for Amsterdam." },
  { id: "eu07", name: "da Matteo", city: "Gotemburgo", country: "Suecia", region: "Europa", tags: ["roastery","specialty","brunch"], hue: 20, rating: 4.7, price: "kr·kr", lat: 57.7075, lng: 11.9671,
    specialty_es: "Icono sueco, tueste propio + brunch", specialty_en: "Swedish icon, in-house roast + brunch",
    quote_es: "«da Matteo define cómo Suecia bebe café moderno. Imprescindible.»",
    quote_en: "\u201cda Matteo defines how Sweden drinks modern coffee. Essential.\u201d",
    own_es: "Café sueco de verdad, sin pretensiones.",
    own_en: "Real Swedish coffee, unpretentious." },
  { id: "eu08", name: "Ditta Artigianale", city: "Florencia", country: "Italia", region: "Europa", tags: ["specialty","third_wave","filter"], hue: 22, rating: 4.6, price: "€€", lat: 43.7696, lng: 11.2558,
    specialty_es: "Rebelión italiana contra el espresso blando", specialty_en: "Italian rebellion against weak espresso",
    quote_es: "«Florencia encontró su café serio en Ditta. Espresso como debería ser.»",
    quote_en: "\u201cFlorence found its serious coffee at Ditta. Espresso as it should be.\u201d",
    own_es: "Café italiano que no se arrodilla ante la tradición.",
    own_en: "Italian coffee that doesn't bow to tradition." },
  { id: "eu09", name: "Copenhagen Coffee Lab", city: "Lisboa", country: "Portugal", region: "Europa", tags: ["specialty","outdoor"], hue: 24, rating: 4.7, price: "€€", lat: 38.7223, lng: -9.1393,
    specialty_es: "Tueste danés en Portugal, fusión perfecta", specialty_en: "Danish roasting in Portugal, perfect fusion",
    quote_es: "«Lisboa necesitaba un café así. Danés y portugués en perfecta armonía.»",
    quote_en: "\u201cLisbon needed a coffee like this. Danish and Portuguese in perfect harmony.\u201d",
    own_es: "Nordic en el corazón portugués.",
    own_en: "Nordic in a Portuguese heart." },

  // ── ASIA ────────────────────────────────────────────────────────────────
  { id: "as01", name: "Fuglen", city: "Tokio", country: "Japón", region: "Asia", tags: ["filter","third_wave"], hue: 26, rating: 4.9, price: "¥¥", lat: 35.6762, lng: 139.6503,
    specialty_es: "Filtros nórdicos en tienda vintage de los 60", specialty_en: "Nordic filters in a 1960s vintage shop",
    quote_es: "«Entras a Fuglen y el tiempo se detiene. Café y diseño de otra era.»",
    quote_en: "\u201cEnter Fuglen and time stops. Coffee and design from another era.\u201d",
    own_es: "Café noruego en Tokio, sin disculpas.",
    own_en: "Norwegian coffee in Tokyo, no apologies." },
  { id: "as02", name: "% Arabica", city: "Kioto", country: "Japón", region: "Asia", tags: ["specialty","matcha"], hue: 28, rating: 4.6, price: "¥¥", lat: 35.0116, lng: 135.7681,
    specialty_es: "Latte de Kioto con río Kamogawa de fondo", specialty_en: "Kyoto latte with Kamogawa river backdrop",
    quote_es: "«La cola merece la pena. El río, el café, la paz. Kioto en una taza.»",
    quote_en: "\u201cThe queue is worth it. The river, the coffee, the peace. Kyoto in a cup.\u201d",
    own_es: "Ver el mundo a través del café.",
    own_en: "See the world through coffee." },
  { id: "as03", name: "Fritz Coffee", city: "Seúl", country: "Corea del Sur", region: "Asia", tags: ["specialty","third_wave","pastry"], hue: 30, rating: 4.7, price: "₩₩", lat: 37.5665, lng: 126.9780,
    specialty_es: "Icono del specialty coreano, latte art premiado", specialty_en: "Korean specialty icon, award-winning latte art",
    quote_es: "«Seúl respira café en Fritz. El latte art es una firma de artista.»",
    quote_en: "\u201cSeoul breathes coffee at Fritz. The latte art is an artist's signature.\u201d",
    own_es: "Café coreano de clase mundial.",
    own_en: "World-class Korean coffee." },
  { id: "as04", name: "Roots Coffee Roaster", city: "Bangkok", country: "Tailandia", region: "Asia", tags: ["roastery","specialty"], hue: 32, rating: 4.6, price: "฿฿", lat: 13.7563, lng: 100.5018,
    specialty_es: "Café tailandés de origen, tueste propio en Thonglor", specialty_en: "Thai single-origin, in-house roasting in Thonglor",
    quote_es: "«Descubrir café tailandés serio cambió mi perspectiva. Roots es la prueba.»",
    quote_en: "\u201cDiscovering serious Thai coffee changed my perspective. Roots is the proof.\u201d",
    own_es: "Café tailandés para el mundo.",
    own_en: "Thai coffee for the world." },
  { id: "as05", name: "Simple Kaffa", city: "Taipei", country: "Taiwán", region: "Asia", tags: ["specialty","filter","third_wave"], hue: 34, rating: 4.8, price: "NT$", lat: 25.0443, lng: 121.5093,
    specialty_es: "Campeón mundial barista 2016, filtros de obsesión", specialty_en: "2016 World Barista Champion, obsessive filters",
    quote_es: "«El campeón del mundo hace filtros en Taipei. Cada taza es un monumento.»",
    quote_en: "\u201cThe world champion makes filters in Taipei. Every cup is a monument.\u201d",
    own_es: "Café como verdad universal.",
    own_en: "Coffee as universal truth." },

  // ── NORTEAMÉRICA ────────────────────────────────────────────────────────
  { id: "na01", name: "Blue Bottle Coffee", city: "Nueva York", country: "EE. UU.", region: "Norteamérica", tags: ["specialty","filter","third_wave"], hue: 36, rating: 4.6, price: "$$", lat: 40.7235, lng: -73.9961,
    specialty_es: "Pionero de la precisión, pour-over instantáneo", specialty_en: "Precision pour-over pioneer",
    quote_es: "«Blue Bottle inventó cómo se supone que debe saber el café. Cada taza.»",
    quote_en: "\u201cBlue Bottle invented how coffee is supposed to taste. Every cup.\u201d",
    own_es: "Café fresco en 48 horas o no lo servimos.",
    own_en: "Fresh coffee within 48 hours or we don't serve it." },
  { id: "na02", name: "Stumptown Coffee", city: "Portland", country: "EE. UU.", region: "Norteamérica", tags: ["roastery","specialty"], hue: 38, rating: 4.7, price: "$$", lat: 45.5218, lng: -122.6745,
    specialty_es: "Pionero comercio directo, tercera ola nacida aquí", specialty_en: "Direct trade pioneer, third wave birthplace",
    quote_es: "«Portland respira Stumptown. El cold brew que crearon define Portland.»",
    quote_en: "\u201cPortland breathes Stumptown. The cold brew they invented defines the city.\u201d",
    own_es: "Relaciones directas con productores desde el año 2000.",
    own_en: "Direct relationships with producers since 2000." },
  { id: "na03", name: "Intelligentsia", city: "Chicago", country: "EE. UU.", region: "Norteamérica", tags: ["roastery","specialty","third_wave"], hue: 16, rating: 4.6, price: "$$", lat: 41.8781, lng: -87.6298,
    specialty_es: "Pionero comercio directo EE. UU., black cat espresso", specialty_en: "US direct trade pioneer, black cat espresso",
    quote_es: "«Intelligentsia cambió cómo Chicago bebe espresso. El Black Cat es legendario.»",
    quote_en: "\u201cIntelligentsia changed how Chicago drinks espresso. The Black Cat is legendary.\u201d",
    own_es: "Café extraordinario, directamente negociado.",
    own_en: "Extraordinary coffee, directly negotiated." },
  { id: "na04", name: "Devoción", city: "Brooklyn", country: "EE. UU.", region: "Norteamérica", tags: ["roastery","specialty"], hue: 18, rating: 4.7, price: "$$", lat: 40.6782, lng: -73.9442,
    specialty_es: "Café colombiano volado semanalmente, frescura radical", specialty_en: "Colombian beans flown weekly, radical freshness",
    quote_es: "«Finca a taza en 10 días. Devoción inventó la frescura en café.»",
    quote_en: "\u201cFarm to cup in 10 days. Devoción invented freshness in coffee.\u201d",
    own_es: "De finca a taza en menos de 10 días.",
    own_en: "Farm to cup in under 10 days." },
  { id: "na05", name: "Café Avellaneda", city: "Ciudad de México", country: "México", region: "Latinoamérica", tags: ["specialty","third_wave"], hue: 20, rating: 4.6, price: "$$", lat: 19.4326, lng: -99.1332,
    specialty_es: "Tostador de referencia, Oaxaca y Chiapas", specialty_en: "Benchmark roaster, Oaxaca and Chiapas",
    quote_es: "«El mejor café de Ciudad de México, sin discusión. Avellaneda lo demuestra.»",
    quote_en: "\u201cThe best coffee in Mexico City, no debate. Avellaneda proves it.\u201d",
    own_es: "Contamos las historias de quienes cultivan café mexicano.",
    own_en: "We tell the stories of those who grow Mexican coffee." },

  // ── LATINOAMÉRICA ───────────────────────────────────────────────────────
  { id: "la01", name: "Azahar Coffee", city: "Bogotá", country: "Colombia", region: "Latinoamérica", tags: ["specialty","roastery"], hue: 22, rating: 4.7, price: "$$", lat: 4.7110, lng: -74.0087,
    specialty_es: "Café de finca propia, catación abierta, raíces colombianas", specialty_en: "Farm-to-cup coffee, open cuppings, Colombian roots",
    quote_es: "«Nunca entendí el café colombiano hasta Azahar. La catación abierta es reveladora.»",
    quote_en: "\u201cI never understood Colombian coffee until Azahar. The open cupping is revelatory.\u201d",
    own_es: "De nuestra finca a tu taza, sin intermediarios.",
    own_en: "From our farm to your cup, no middlemen." },

  // ── OCEANÍA ─────────────────────────────────────────────────────────────
  { id: "oc01", name: "Proud Mary", city: "Melbourne", country: "Australia", region: "Oceanía", tags: ["specialty","third_wave","brunch"], hue: 24, rating: 4.8, price: "$$", lat: -37.8136, lng: 144.9631,
    specialty_es: "Brunch australiano, filtros de competición", specialty_en: "Australian brunch, competition-grade filters",
    quote_es: "«Vale el viaje en avión. La experiencia del café aquí es incomparable.»",
    quote_en: "\u201cWorth a flight. The coffee experience here is incomparable.\u201d",
    own_es: "Hospitalidad radical y café que respeta al productor.",
    own_en: "Radical hospitality and coffee that respects the farmer." },
  { id: "oc02", name: "Padre Coffee", city: "Melbourne", country: "Australia", region: "Oceanía", tags: ["roastery","specialty"], hue: 26, rating: 4.6, price: "$$", lat: -37.8100, lng: 144.9640,
    specialty_es: "Institución Melbourne, brunch + espresso", specialty_en: "Melbourne institution, brunch + espresso",
    quote_es: "«Padre Coffee es Melbourne. El flat white es perfecto, el brunch, legendario.»",
    quote_en: "\u201cPadre Coffee is Melbourne. The flat white is perfect, the brunch is legendary.\u201d",
    own_es: "Café de especialidad con alma de barrio.",
    own_en: "Specialty coffee with a neighborhood soul." },

  // ── ÁFRICA ──────────────────────────────────────────────────────────────
  { id: "af01", name: "Truth Coffee Roasting", city: "Ciudad del Cabo", country: "Sudáfrica", region: "África", tags: ["roastery","specialty"], hue: 28, rating: 4.7, price: "R·R", lat: -33.9249, lng: 18.4241,
    specialty_es: "Tostador steampunk, mejor cafetería del mundo una vez", specialty_en: "Steampunk roaster, once world's best coffee shop",
    quote_es: "«Truth es una experiencia sensorial. Steampunk y café de verdad convergen.»",
    quote_en: "\u201cTruth is a sensory experience. Steampunk and real coffee converge.\u201d",
    own_es: "Café africano tostado con orgullo africano.",
    own_en: "African coffee roasted with African pride." },
  { id: "af02", name: "Tomoca", city: "Adís Abeba", country: "Etiopía", region: "África", tags: ["specialty","third_wave"], hue: 30, rating: 4.5, price: "Br", lat: 9.0320, lng: 38.7469,
    specialty_es: "Cuna del café desde 1953, experiencia etíope", specialty_en: "Coffee's birthplace since 1953, Ethiopian experience",
    quote_es: "«En la cuna del café. Tomoca es la puerta a la historia del café.»",
    quote_en: "\u201cIn coffee's birthplace. Tomoca is the gateway to coffee history.\u201d",
    own_es: "Café etíope en la tierra donde todo comenzó.",
    own_en: "Ethiopian coffee where it all began." },
];

// Affiliate / recommendation cards. Editorial picks the team recommends for at-home brewing.
const AFFILIATES = [
  { id: "a1", cat: "espresso", brand: "De'Longhi", model: "Dedica EC685",
    name_es: "Cafetera espresso semiautomática", name_en: "Semi-auto espresso machine",
    price: "€349", oldPrice: "€429", rating: 4.6, reviews: 4128, badge: "best",
    url: "https://www.amazon.es/s?k=Delonghi+Dedica+EC685&tag=vladys-21",
    note_es: "Nuestra recomendación para empezar a hacer espresso en casa. Caldera rápida y portafiltros profesional.",
    note_en: "Our pick to start pulling espresso at home. Fast boiler and pro-grade portafilter.",
    hue: 16 },
  { id: "a2", cat: "grinder", brand: "1Zpresso", model: "JX-Pro",
    name_es: "Molinillo manual cónico", name_en: "Manual conical burr grinder",
    price: "€189", oldPrice: null, rating: 4.8, reviews: 2641, badge: "editor",
    url: "https://www.amazon.es/s?k=1Zpresso+JX-Pro&tag=vladys-21",
    note_es: "Recomendado por casi todos los baristas que entrevistamos. Muelas de acero y ajuste por clicks.",
    note_en: "Recommended by nearly every barista we interviewed. Steel burrs, click-stepped adjustment.",
    hue: 28 },
  { id: "a3", cat: "beans", brand: "Specialty", model: "Café en grano 1kg",
    name_es: "Café de especialidad en grano — 1kg", name_en: "Specialty whole bean coffee — 1kg",
    price: "€22", oldPrice: null, rating: 4.7, reviews: 538, badge: "fresh",
    url: "https://www.amazon.es/s?k=cafe+especialidad+grano+1kg&tag=vladys-21",
    note_es: "Busca café recién tostado con fecha de tueste visible. Notas frutales, chocolate y frutos secos.",
    note_en: "Look for freshly roasted coffee with visible roast date. Fruity, chocolate, and nutty notes.",
    hue: 22 },
  { id: "a4", cat: "kettle", brand: "Hario", model: "V60 Buono",
    name_es: "Tetera de cuello de cisne 1L", name_en: "Gooseneck pour-over kettle 1L",
    price: "€59", oldPrice: "€72", rating: 4.7, reviews: 1893, badge: "favorite",
    url: "https://www.amazon.es/s?k=Hario+V60+Buono&tag=vladys-21",
    note_es: "El básico para filtrar V60. Pico fino, control absoluto sobre el flujo.",
    note_en: "The pour-over staple. Fine spout, total control over the flow.",
    hue: 36 },
  { id: "a5", cat: "grinder", brand: "Baratza", model: "Encore ESP",
    name_es: "Molinillo eléctrico para espresso", name_en: "Electric espresso grinder",
    price: "€169", oldPrice: "€199", rating: 4.5, reviews: 1247, badge: "best",
    url: "https://www.amazon.es/s?k=Baratza+Encore+molinillo+cafe&tag=vladys-21",
    note_es: "El molinillo eléctrico con mejor relación calidad-precio para espresso. Muelas cónicas de 40mm.",
    note_en: "Best value electric grinder for espresso. 40mm conical burrs.",
    hue: 30 },
  { id: "a6", cat: "espresso", brand: "Bialetti", model: "Moka Express 6 tazas",
    name_es: "Cafetera italiana clásica", name_en: "Classic Italian moka pot",
    price: "€32", oldPrice: null, rating: 4.7, reviews: 8432, badge: "favorite",
    url: "https://www.amazon.es/s?k=Bialetti+Moka+Express+6+tazas&tag=vladys-21",
    note_es: "La cafetera que nunca falla. Aluminio original, hecha en Italia, para 6 tazas.",
    note_en: "The failproof coffee maker. Original aluminum, made in Italy, 6-cup.",
    hue: 14 },
];

// Chill Zone — fake "now playing" tracks
const TRACKS = [
  { id: "t1", title: "Espresso machine, 8 a.m.", duration: "12:04", kind: "ASMR" },
  { id: "t2", title: "Lo-fi study session, vol. III", duration: "47:21", kind: "Lo-fi" },
  { id: "t3", title: "Rain on the awning", duration: "31:08", kind: "ASMR" },
  { id: "t4", title: "Slow morning, jazz piano", duration: "28:55", kind: "Jazz" },
];

window.I18N = I18N;
window.LOCAL_CAFE = LOCAL_CAFE;
window.CAFES = CAFES;
window.AFFILIATES = AFFILIATES;
window.TRACKS = TRACKS;
